name: Verificacion users

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del código
      uses: actions/checkout@v2
      
    - name: Ejecutar un comando de ejemplo
      run: echo "Hola, mundo!"
